version: '3.9'

services:
  db:
    image: mariadb:10.11
    container_name: tolo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tolo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: php:8.2-apache
    container_name: tolo_backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: tolo_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
